if [ -f ~/.config/sops/age/keys.txt ]; then
	export SOPS_AGE_KEY_FILE=~/.config/sops/age/keys.txt
fi

kn() {
	if [ "$1" != "" ]; then
		kubectl config set-context --current --namespace=$1
	else
		echo -e "\e[1;31m Error, please provide a valid Namespace\e[0m"
	fi
}

knd() {
	kubectl config set-context --current --namespace=default
}

ku() {
	kubectl config unset current-context
}
